### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Ums)
add_subdirectory(UmsContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Umsplugin
    UmsContentplugin
    QtQuickDesignerComponents)